### ISSUE TITLE
Chopping off one pixel at the end of each segment in EDPF::ExtractNewSegments()

### ISSUE THREAD

**Issue by tobbelobb** [CihanTopal/ED_Lib#15]
https://github.com/CihanTopal/ED_Lib/blob/7f171db0321de67b12ee3d0558b0b1d60122000d/EDPF.cpp#L219

My fork is getting so refactored that it's a bit hard to translate back to original ED_Lib now, but I think the referenced line is in error. I think it should just say `end`, instead of `end - 1`.

The corresponding line in my code is here:
https://gitlab.com/tobben/hpm/-/blob/b079a6f824984bc89cc7df5ed1247974fda99dbe/hpm/ed/EDCommon.c++#L33

The issue is easiest to see and to validate manually in very short segments. This is the edgeImage:
![Selection_068](https://user-images.githubusercontent.com/5753253/107640883-33bd1280-6c73-11eb-90a0-93fecc56f824.png)

This is the validated segment when using `end - 1`.
![Selection_066](https://user-images.githubusercontent.com/5753253/107640696-f3f62b00-6c72-11eb-828f-09b5ccf3a813.png)

This is the same segment with `end - 1` changed to `end`:
![Selection_067](https://user-images.githubusercontent.com/5753253/107641018-5e0ed000-6c73-11eb-8eaf-9090c7069912.png)

Changing this makes EDCircles find more circles.

Please stop me if the copping of that last pixel is intentional, which it very well might be.

Ironically, from a top level view, the performance of my particular application got worse, since more (real) circles were found, that it had to filter away. I balanced this back by lowering `LONG_ARC_ERROR` in EDCircles.cpp.

**Comment by sturkmen72** [comment]
@tobbelobb Thank you. Your proposal seems correct.
see commit : 65dedf08e86d7a0eff89cef7717c553208e6fa14
