### ISSUE TITLE
buffer size too small

### ISSUE THREAD

**Issue by YusukeSuzuki** [CihanTopal/ED_Lib#17]
For large size image, EDLines buffer sizes are some times too small and constructor overruns.

In my use, I've fixed the lines as bellow. 
https://github.com/CihanTopal/ED_Lib/blob/745472f4316da13da38197adb4aba633143c1fcd/EDLines.cpp#L24

```cpp
    size_t buffer_size = 1; 

    for (int segmentNumber = 0; segmentNumber < segmentPoints.size(); segmentNumber++) {
        auto segment_size = segmentPoints[segmentNumber].size();
        buffer_size = std::max(buffer_size, segment_size);
    }    

    double *x = new double[buffer_size];
    double *y = new double[buffer_size];
```

**Comment by wickeat** [comment]
I have also encountered the same problem. @YusukeSuzuki your suggestion works, thanks!
