### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by krishenm94** [CihanTopal/ED_Lib#2]
Hey, there doesn't seem to be a license file in this repo??

**Comment by CihanTopal** [comment]
Hi. You can find the the license information is at the end of the readme file under the title "Disclaimer for Edge Drawing Library".

**Comment by krishenm94** [comment]
Could you please add a proper license file such as mit, apache, lgpl,gpl, etc. Otherwise it makes it hard to use this code in any project.

**Comment by krishenm94** [comment]
bump

**Comment by syaifulnizamyahya** [comment]
A distributed license file would be nice.

**Comment by CihanTopal** [comment]
A license file (MIT) is added.
