### ISSUE TITLE
Memory leak， Process finished with exit code 137 (interrupted by signal 9: SIGKILL) 

### ISSUE THREAD

**Issue by hlcool** [CihanTopal/ED_Lib#22]
EdgeDrawing algorithm is great，
but i find that the EdgeDrawing algorithm in opencv contrib, as the program runs, the memory usage is increasing

**Comment by sturkmen72** [comment]
@hlcool i am still working on porting EDLib into OpenCV. [the firsts patch]((https://github.com/opencv/opencv_contrib/commit/f5aeecf2da2d040fce649d1039af3f6f7368cd14)) is merged recently. i hope i will complete porting all functionality soon.

**Comment by sturkmen72** [comment]
![Adsız1](https://user-images.githubusercontent.com/12151541/115597529-07acb600-a2e2-11eb-9b04-c91c9f9af072.jpg)
you are right as seen above.

fortunately it is fixed. and speeded up as seen below 

![ed-test](https://user-images.githubusercontent.com/12151541/115598012-9b7e8200-a2e2-11eb-9486-fa5f8e3e11a6.jpg)

**Comment by hlcool** [comment]
great
Speed increased by 2 times
