### ISSUE TITLE
why different opencv?

### ISSUE THREAD

**Issue by SueeH** [CihanTopal/ED_Lib#26]
Thanks for great job for line and circle detection.
After run test_ED, opencv(4.5.2) & EDLIB show different run time but same results(no diff between pixel), as follows: 
            testED.getEdgeImage()  (Original)  : 48.5386
            detectEdges()            (OpenCV)  : 15.8752
            different pixel count              : 0
            -------------------------------------------------
            testEDLines.getLineImage()         : 7.61791
            detectLines()            (OpenCV)  : 22.7407
            different pixel count              : 0
Also, opencv consumes less total time(include detectEdge and detectLine). Any difference in function implemention？

**Comment by sturkmen72** [comment]
maybe you will get slight pixel differences if you try another image.
the reason OpenCV and original code uses different nfa computation.
anyway i am still working on the code to get better and all feedback is appreciated.

**Comment by SueeH** [comment]
Thank you for your reply!
I will try different input and follow your works.
Best wishes！
