### ISSUE TITLE
CMake Error: target name "test" is reserved

### ISSUE THREAD

**Issue by 4c3y** [CihanTopal/ED_Lib#33]
I would like to include ED_Lib as a git submodule in my project but I get the following error:

```
CMake Error at 3rdparty/ED_Lib/CMakeLists.txt:24 (add_executable):
  The target name "test" is reserved when CTest testing is enabled.
```

This error occurs as a result of the following code in `CMakeLists.txt`:
```CMake 
add_executable(test test.cpp)
target_link_libraries(test ${OpenCV_LIBS} EDLib)
```

CMake includes some functionality for automated testing so the name "test" is reserved. Would it be possible to rename the target "test" into something else?

**Comment by sturkmen72** [comment]
done.
