### ISSUE TITLE
check case 

### ISSUE THREAD

**Issue by maddin200** [CihanTopal/ED_Lib#36]
ED.cpp line 336

Code:
case SCHARR_OPERATOR:
	gx = abs(3 * (com1 + com2) + 10 * (smoothImg[i*width + j + 1] - smoothImg[i*width + j - 1]));
	gy = abs(3 * (com1 - com2) + 10 * (smoothImg[(i + 1)*width + j] - smoothImg[(i - 1)*width + j])); // <-- break missing ?
case LSD_OPERATOR:

**Comment by sturkmen72** [comment]
@maddin200 thank you.
