### ISSUE TITLE
incorrect comment in circle linear equation

### ISSUE THREAD

**Issue by GGain** [CihanTopal/ED_Lib#5]
At line 2968 in file EDCircles.cpp, there is a mistake.

 // |N    Suv| |uc| = |b1|
// |Suv  Svv| |vc| = |b2|

It should be:

// |Suu    Suv| |uc| = |b1|
// |Suv  Svv| |vc| = |b2|

**Comment by CagriUysal** [comment]
Please consider opening a pull request about your concern.
We would appreciate any contribution whether it's a typo fix, bug fix, etc..
Thank you.
