### ISSUE TITLE
MIT license conflict with header file GPLv3 license

### ISSUE THREAD

**Issue by luqiang360** [CihanTopal/ED_Lib#7]
https://github.com/CihanTopal/ED_Lib/blob/7f171db0321de67b12ee3d0558b0b1d60122000d/EDLines.h#L7
Hi, License in the header file is `GPLv3`, and there exists an sole [MIT](https://github.com/CihanTopal/ED_Lib/blob/master/LICENSE) license file, and license information at the end of the readme file is `Please contact for commercial use`. The three of them are in conflict, which one should we observe?

**Comment by CihanTopal** [comment]
- GPL license statements in the comments were removed. 
- The statement regarding the commercial use at the end of the readme file were also removed.
- Now it only depends on the MIT license.
